import { Menu } from './menu.model';

export const verticalMenuItems = [ 
    // new Menu (1, 'Dashboard', null, null, 'home', null, true, 0),
    // new Menu (1, 'Claim-Dashboard', '/dashboard', null, null, null, false, 1),
  //  new Menu (2, 'Operational-Dashboard', '/operational-dashboard', null, null, null,false, 1),
    new Menu (2, 'Agency', '/csp', null, 'briefcase', null, false, 0),
    // new Menu (3, 'Intake Process', null, null, 'user-plus', null, true, 0),
    // new Menu (4, 'Client-Intake Form', '/client-intake-form', null, 'user-plus', null, false, 3,),
    // new Menu (5, 'Intake Management', '/process-management', null, 'th-list', null, false, 3),
    new Menu (6, 'Client Information', null, null, 'user-circle', null, true, 0),
    new Menu (7, 'Client', '/client-parent', null, null, null, false, 6),
    // new Menu (8, 'Service Evaluation', '/service-evaluation', null, null, null, false, 6),
    new Menu (9, 'Employee', '/employee', null, 'user', null, false, 0),
    new Menu (10, 'User', '/users', null, 'users', null, false, 0),   
    new Menu (11, 'Billing Timesheets', null, null, 'bookmark', null, true, 0),   
    new Menu (1,  'Timesheets', '/timesheets', null, null, null, false, 11),
    // new Menu (2,  'QP-Timesheets', '/qptimesheet', null, null, null, false, 11),
    new Menu (3, 'Timesheet Verification', '/timesheetverification', null, null, null, false, 11), 
    new Menu (4, 'Claims', '/batch', null, null, null, false, 11),
    new Menu (5, 'Import Payments', '/import', null, null, null, false, 11),
    // new Menu (6, 'Payroll', '/timesheetnew', null, null, null, false, 11),
    // new Menu (7, 'Locked Payroll', '/lockedpayroll', null, null, null, false, 11),
    // new Menu (8, 'Evv Timesheet', '/evv-timesheets', null, null, null, false, 11),
     new Menu (18, 'Roles and Permissions', null, null, 'check-square', null, true, 0),
    // new Menu (19, 'Agency Permissions', '/roles', null, null, null, false, 18),
    new Menu (20, 'Support Management', null, null, 'th-large', null, true, 0),
    new Menu (1, 'Care Coordinator', '/care-coordinator', null, null, null, false, 20),
    new Menu (2, 'Case Manager', '/case-manager', null, null, null, false, 20),    
    new Menu (3, 'Clearing House', '/clearing-house', null, null, null, false, 20),
    new Menu (4, 'Discharge Code', '/dccodes', null, null, null, false, 20),
    new Menu (5, 'ICD10 Code', '/icd10', null, null, null, false, 20),    
    new Menu (6, 'Group Payor', '/group-payor', null, null, null, false, 20),
    new Menu (7, 'Group Payor Service', '/group-payor-service', null, null, null, false, 20),
    new Menu (8, 'List', '/list', null, null, null, false, 20),
    new Menu (9, 'Lov', '/lov', null, null, null, false, 20),
    new Menu (0, 'Manage Service', '/manage-service', null, null, null, false, 20),
    new Menu (11, 'Menus', '/menu', null, null, null, false, 20),   
    new Menu (12, 'Zip Code', '/zip-codes', null, null, null, false, 20),
    new Menu (33, 'Settings', '/setting', null, 'cog', null, false, 0),
    new Menu (34, 'Reports', '/reports', null, 'file', null, false, 0),


    ]

    export const agencyverticalMenuItems = [ 
        // new Menu (2, 'Agency', '/csp', null, 'briefcase', null, false, 0),
        // new Menu (3, 'Intake Process', null, null, 'user-plus', null, true, 0),
        // new Menu (4, 'Client-Intake Form', '/client-intake-form', null, 'user-plus', null, false, 3,),
        // new Menu (5, 'Intake Management', '/process-management', null, 'th-list', null, false, 3),
        new Menu (6, 'Client Information', null, null, 'user-circle', null, true, 0),
        new Menu (7, 'Client', '/client-parent', null, null, null, false, 6),
        // new Menu (8, 'Service Evaluation', '/service-evaluation', null, null, null, false, 6),
        new Menu (9, 'Employee', '/employee', null, 'user', null, false, 0),
        new Menu (10, 'User', '/users', null, 'users', null, false, 0),   
        new Menu (11, 'Billing Timesheets', null, null, 'bookmark', null, true, 0),   
        new Menu (12,  'Timesheets', '/timesheets', null, null, null, false, 11),
        new Menu (13, 'Timesheet Verification', '/timesheetverification', null, null, null, false, 11), 
        new Menu (14, 'Claims', '/batch', null, null, null, false, 11),
        new Menu (15, 'Import Payments', '/import', null, null, null, false, 11),
        // new Menu (16, 'Payroll', '/timesheetnew', null, null, null, false, 11),
        // new Menu (17, 'Locked Payroll', '/lockedpayroll', null, null, null, false, 11),
        // new Menu (1,  'QP-Timesheets', '/qptimesheet', null, null, null, false, 0),
        // new Menu (18, 'Roles and Permissions', null, null, 'check-square', null, true, 0),
        // new Menu (19, 'Agency Permissions', '/roles', null, null, null, false, 18),
        new Menu (20, 'Support Management', null, null, 'th-large', null, true, 0),
        new Menu (21, 'Care Coordinator', '/care-coordinator', null, null, null, false, 20),
        new Menu (22, 'Case Manager', '/case-manager', null, null, null, false, 20),    
        new Menu (23, 'Clearing House', '/clearing-house', null, null, null, false, 20),
        new Menu (24, 'Discharge Code', '/dccodes', null, null, null, false, 20),
        // new Menu (25, 'ICD10 Code', '/icd10', null, null, null, false, 20),    
        new Menu (26, 'Group Payor', '/group-payor', null, null, null, false, 20),
        new Menu (27, 'Group Payor Service', '/group-payor-service', null, null, null, false, 20),
        // new Menu (28, 'List', '/list', null, null, null, false, 20),
        new Menu (29, 'Lov', '/lov', null, null, null, false, 20),
        new Menu (30, 'Manage Service', '/manage-service', null, null, null, false, 20),
        // new Menu (31, 'Menus', '/menu', null, null, null, false, 20),   
        // new Menu (32, 'Zip Code', '/zip-codes', null, null, null, false, 20),
        // new Menu (33, 'Settings', '/setting', null, 'cog', null, false, 0),
    new Menu (34, 'Reports', '/reports', null, 'file', null, false, 0),
    
         ]

export const horizontalMenuItems = [ 
  new Menu (1, 'Dashboard', '/operational-dashboard', null, 'home', null, false, 0),
    // new Menu (2, 'Dashboard', '/agent', null, 'home', null, false, 0),
     new Menu (3, 'Agency', '/csp', null, 'briefcase', null, false, 0),
   //  new Menu (5, 'Intake Form', '/client-intake-form', null, 'user-plus', null, false, 0,),
     new Menu (4, 'Client Information', null, null, 'user-circle', null, true, 0),
     new Menu (5, 'Client', '/client-parent', null, null, null, false, 3),
    // new Menu (14, 'Service Evaluation', '/service-evaluation', null, null, null, false, 3),
     new Menu (6, 'Employee', '/employee', null, 'user', null, false, 0),
     new Menu (7, 'User', '/users', null, 'users', null, false, 0),
     // new Menu (8, 'Process Management', '/cashin', null, 'th-list', null, false, 0),
     // new Menu (9, 'Roles and Permissions', null, null, 'check-square', null, true, 0),
     // new Menu (15, 'Agency Permissions', '/cashin', null, null, null, false, 9),
     new Menu (8, 'Billing Timesheets', null, null, 'bookmark', null, true, 0),   
     new Menu (9,  'Timesheets', '/timesheets', null, null, null, false, 12),
    //  new Menu (1,  'QP-Timesheets', '/qptimesheet', null, null, null, false, 0),
     new Menu (10, 'Timesheet Verification', '/timesheetverification', null, null, null, false, 12), 
     new Menu (11, 'Claims', '/batch', null, null, null, false, 12),
     new Menu (12, 'Import Payments', '/import', null, null, null, false, 12),
     new Menu (13, 'Support Management', null, null, 'th-large', null, true, 0),
     new Menu (14, 'Care Coordinator', '/care-coordinator', null, null, null, false, 10),
     new Menu (15, 'Case Manager', '/case-manager', null, null, null, false, 10),    
     new Menu (16, 'Clearing House', '/clearing-house', null, null, null, false, 10),
     new Menu (17, 'Discharge Code', '/dccodes', null, null, null, false, 10),
     new Menu (18, 'ICD10 Code', '/icd10', null, null, null, false, 10),    
     new Menu (19, 'Group Payor', '/group-payor', null, null, null, false, 10),
     new Menu (20, 'Group Payor Service', '/group-payor-service', null, null, null, false, 10),
     new Menu (21, 'List', '/list', null, null, null, false, 10),
     new Menu (22, 'Lov', '/lov', null, null, null, false, 10),
     new Menu (23, 'Manage Service', '/manage-service', null, null, null, false, 10),
     new Menu (24, 'Menus', '/menu', null, null, null, false, 10),
    //  new Menu (11, 'Settings', '/setting', null, 'cog', null, false, 0),   
     new Menu (25, 'Zip Code', '/zip-codes', null, null, null, false, 10),
     // new Menu (32, 'Payroll', '/cashin', null, null, null, false, 12),
    new Menu (34, 'Reports', '/reports', null, 'file', null, false, 0),
    new Menu (35, 'Frequency Schedule', '/frequency', null, 'file', null, false, 0),
]
